### Rota para pegar os produtos
GET http://localhost:3000/produtos

### fechando a requicisao

### Rota criando o produto
POST http://localhost:3000/produtos
Content-Type: application/json

{
    "nome":"GTX 4090 24gb",
    "preco":14450,
    "quantidade":12
}

###
GET http://localhost:3000/produtos/2
Content-Type: application/json

###
PUT http://localhost:3000/produtos/2
Content-Type: application/json

{
    "novoNome": "GTX 5090 24gb",
    "novoPreco":32450,
    "novaQuantidade":63
}

###
DELETE http://localhost:3000/produtos/2
Content-Type: application/json

###
DELETE http://localhost:3000/produtos